title: "Bayraktar Yatırım Danışmanlık"
description: "Emlak ve İnşaat sektöründe güvenilir, şeffaf ve kaliteli hizmet"

remote_theme: pages-themes/architect@v0.3.0

plugins:
  - jekyll-remote-theme

url: "https://budiay.github.io/bayraktaryatirimdanismanlik"
baseurl: "/bayraktaryatirimdanismanlik"

lang: "tr"
