title: "Bayraktar Yatırım Danışmanlık"
description: "Emlak ve İnşaat sektöründe güvenilir, şeffaf ve kaliteli hizmet"

remote_theme: pages-themes/architect@v0.3.0

plugins:
  - jekyll-remote-theme

# Sosyal medya ikonları (footer için görünür olabilir)
social:
  twitter: your_twitter_username
  linkedin: your_linkedin_profile
  instagram: your_instagram_username

# Site URL (GitHub Pages linkin)
url: "https://budiay.github.io"
baseurl: "/bayraktaryatirimdanismanlik"

# SEO ve meta ayarları
seo:
  type: "organization"
  name: "Bayraktar Yatırım Danışmanlık"
  description: "Emlak ve İnşaat sektöründe güvenilir, şeffaf ve kaliteli hizmet sunuyoruz."
  logo: "/assets/images/logo.png"  # Bu dosyayı ilgili dizine yüklemelisin.

# Footer mesajı
footer:
  message: "© 2025 Bayraktar Yatırım Danışmanlık. Güvenle evinizi seçin, geleceğinizi kurun."

# Varsayılan dil
lang: "tr"
